// Code generated by gtml; DO NOT EDIT.
// v0.1.0 | you may see errors with types, you'll need to manage your own imports
// type support coming soon!

package main

import "strings"



func gtmlFor[T any](slice []T, callback func(i int, item T) string) string {
	var builder strings.Builder
	for i, item := range slice {
		builder.WriteString(callback(i, item))
	}
	return builder.String()
}

func gtmlIf(condition bool, fn func() string) string {
if condition {
	return fn()
}
	return ""
}

func gtmlElse(condition bool, fn func() string) string {
	if !condition {
		return fn()
	}
	return ""
}

func gtmlSlot(contentFunc func() string) string {
	return contentFunc()
}

func gtmlEscape(input string) string {
	return input
}

func Layout(title string, test string) string {
	layout := func() string {
		var layoutBuilder strings.Builder
		mainheaderPlaceholder1 := func() string {
			testSlot2 := gtmlSlot(func() string {
				var testBuilder strings.Builder
				testBuilder.WriteString(`<div _slot="test" _id="2"><p>testing!</p></div>`)
				return testBuilder.String()
			})
			return MainHeader(testSlot2)
		}
		layoutBuilder.WriteString(`<html _component="Layout" _id="0"><head><meta name="viewport" content="width=device-width, initial-scale=1"/><meta charset="UTF-8"/><link rel="stylesheet" href="/static/css/output.css"/><script src="/static/js/staci.js"></script><title>`)
		layoutBuilder.WriteString(title)
		layoutBuilder.WriteString(`</title></head><body><div class="flex flex-col gap-4">`)
		layoutBuilder.WriteString(mainheaderPlaceholder1())
		layoutBuilder.WriteString(`</div><header _component="MainHeader" class="p-4 flex flex-col gap-2 border-b" _id="0"><h1 class="font-bold text-2xl">Staci</h1><p class="text-sm">Come visit sometime.. 💄</p>`)
		layoutBuilder.WriteString(test)
		layoutBuilder.WriteString(`</header></body></html>`)
		return layoutBuilder.String()
	}
	return gtmlEscape(layout())
}

func MainHeader(test string) string {
	mainheader := func() string {
		var mainheaderBuilder strings.Builder
		mainheaderBuilder.WriteString(`<header _component="MainHeader" class="p-4 flex flex-col gap-2 border-b" _id="0"><h1 class="font-bold text-2xl">Staci</h1><p class="text-sm">Come visit sometime.. 💄</p>`)
		mainheaderBuilder.WriteString(test)
		mainheaderBuilder.WriteString(`</header>`)
		return mainheaderBuilder.String()
	}
	return gtmlEscape(mainheader())
}

