// Code generated by gtml; DO NOT EDIT.
// +build ignore
// v0.1.0 | you may see errors with types, you'll need to manage your own imports
// type support coming soon!

package components

import "strings"

func gtmlFor[T any](slice []T, callback func(i int, item T) string) string {
var builder strings.Builder
for i, item := range slice {
	builder.WriteString(callback(i, item))
}
return builder.String()
}

func gtmlIf(condition bool, fn func() string) string {
if condition {
	return fn()
}
return ""
}

func gtmlElse(condition bool, fn func() string) string {
if !condition {
	return fn()
}
return ""
}

func gtmlSlot(contentFunc func() string) string {
return contentFunc()
}

func NameTag(firstName string, message string) string {
	var builder strings.Builder
	builder.WriteString(`<div _component="NameTag" _id="0"><h1>`)
	builder.WriteString(firstName)
	builder.WriteString(`</h1><p>`)
	builder.WriteString(message)
	builder.WriteString(`</p></div>`)
	return builder.String()
}

func PlaceholderWithAttrs() string {
	var builder strings.Builder
	nametagPlaceholder0 := func() string {
		return NameTag("gtml", "is the best")
	}
	builder.WriteString(nametagPlaceholder0())
	return builder.String()
}

